/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */

export type CaseAction = {
  type:
    | 'CREATE_PLACEMENT'
    | 'PROVIDE_INFORMATION'
    | 'START_APPROVED_PREMISE_APPLICATION'
    | 'CONTINUE_APPROVED_PREMISE_APPLICATION'
    | 'START_CAS3_REFERRAL'
    | 'REPLY_TO_CAS3_BEDSPACE_OFFER'
    | 'SUBMIT_DTR_BEFORE_CAS3'
    | 'SUBMIT_CRS_BEFORE_CAS3'
    | 'SUBMIT_CRS_ACCOMMODATION_BEFORE_CAS3'
    | 'SUBMIT_DTR_AND_CRS_BEFORE_CAS3'
    | 'SUBMIT_DTR_AND_CRS_ACCOMMODATION_BEFORE_CAS3'
    | 'SUBMIT_DTR_REFERRAL'
    | 'ADD_DTR_REFERRAL_DETAILS'
    | 'ADD_DTR_OUTCOME'
    | 'SUBMIT_CRS_ACCOMMODATION_REFERRAL'
    | 'SUBMIT_CRS_REFERRAL'
    | 'ADD_AND_CONFIRM_PROPOSED_ADDRESS'
  startDate?: string | null
}
