/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */

export type { AccommodationAddressDetails } from './models/AccommodationAddressDetails'
export type { AccommodationDetail } from './models/AccommodationDetail'
export type { AccommodationDetailCommand } from './models/AccommodationDetailCommand'
export type { AccommodationReferralDto } from './models/AccommodationReferralDto'
export type { AccommodationStatusDto } from './models/AccommodationStatusDto'
export type { AccommodationSummaryDto } from './models/AccommodationSummaryDto'
export type { AccommodationTypeDto } from './models/AccommodationTypeDto'
export type { ApiResponseDtoAccommodationDetail } from './models/ApiResponseDtoAccommodationDetail'
export type { ApiResponseDtoAccommodationSummaryDto } from './models/ApiResponseDtoAccommodationSummaryDto'
export type { ApiResponseDtoCaseDto } from './models/ApiResponseDtoCaseDto'
export type { ApiResponseDtoDutyToReferDto } from './models/ApiResponseDtoDutyToReferDto'
export type { ApiResponseDtoEligibilityDto } from './models/ApiResponseDtoEligibilityDto'
export type { ApiResponseDtoListAccommodationDetail } from './models/ApiResponseDtoListAccommodationDetail'
export type { ApiResponseDtoListAccommodationReferralDto } from './models/ApiResponseDtoListAccommodationReferralDto'
export type { ApiResponseDtoListAccommodationSummaryDto } from './models/ApiResponseDtoListAccommodationSummaryDto'
export type { ApiResponseDtoListAuditRecordDto } from './models/ApiResponseDtoListAuditRecordDto'
export type { ApiResponseDtoListCaseDto } from './models/ApiResponseDtoListCaseDto'
export type { ApiResponseDtoListReferenceDataDto } from './models/ApiResponseDtoListReferenceDataDto'
export type { AssignedToDto } from './models/AssignedToDto'
export type { AuditRecordDto } from './models/AuditRecordDto'
export type { CaseDto } from './models/CaseDto'
export type { DlqMessage } from './models/DlqMessage'
export type { DtrCommand } from './models/DtrCommand'
export type { DtrSubmissionDto } from './models/DtrSubmissionDto'
export type { DutyToReferDto } from './models/DutyToReferDto'
export type { EligibilityDto } from './models/EligibilityDto'
export type { FailureIdentifier } from './models/FailureIdentifier'
export type { FieldChange } from './models/FieldChange'
export type { GetDlqResult } from './models/GetDlqResult'
export type { LocalAuthorityDto } from './models/LocalAuthorityDto'
export type { NoteCommand } from './models/NoteCommand'
export type { PurgeQueueResult } from './models/PurgeQueueResult'
export type { ReferenceDataDto } from './models/ReferenceDataDto'
export type { RetryDlqResult } from './models/RetryDlqResult'
export type { ServiceResult } from './models/ServiceResult'
export type { UpstreamFailureDto } from './models/UpstreamFailureDto'
