import { ServiceResult } from '@sas/api'
import { StatusTag } from '@sas/ui'

// eslint-disable-next-line import/prefer-default-export
export const serviceStatusTag = (status?: ServiceResult['serviceStatus']): StatusTag =>
  ({
    NOT_REQUIRED: { text: 'Not required', colour: 'grey' },
    NOT_ELIGIBLE: { text: 'Not eligible', colour: 'grey' },
    CANNOT_START_YET: { text: 'Cannot start yet', colour: 'grey' },
    UPCOMING: { text: 'Upcoming', colour: 'yellow' },
    STARTED: { text: 'Started', colour: 'green' },
    NOT_STARTED: { text: 'Not started', colour: 'orange' },
    NOT_SUBMITTED: { text: 'Not submitted', colour: 'orange' },
    INFO_REQUESTED: { text: 'Info requested', colour: 'yellow' },
    REJECTED: { text: 'Rejected', colour: 'orange' },
    WITHDRAWN: { text: 'Withdrawn', colour: 'grey' },
    SUBMITTED: { text: 'Submitted', colour: 'yellow' },
    PLACEMENT_BOOKED: { text: 'Placement booked', colour: 'green' },
    CONFIRMED: { text: 'Confirmed', colour: 'green' },
    NOT_ARRIVED: { text: 'Not arrived', colour: 'orange' },
    PLACEMENT_CANCELLED: { text: 'Placement cancelled', colour: 'orange' },
    PLACEMENT_REQUEST_NOT_STARTED: { text: 'Placement request not started', colour: 'orange' },
    PLACEMENT_REQUEST_WITHDRAWN: { text: 'Placement request withdrawn', colour: 'orange' },
    PLACEMENT_REQUEST_SUBMITTED: { text: 'Placement request submitted', colour: 'yellow' },
    PLACEMENT_REQUEST_REJECTED: { text: 'Placement request rejected', colour: 'orange' },
    APPLICATION_REJECTED: { text: 'Application rejected', colour: 'orange' },
    ARRIVED: { text: 'Arrived', colour: 'green' },
    BEDSPACE_OFFERED: { text: 'Bedspace offered', colour: 'orange' },
    BOOKING_CONFIRMED: { text: 'Booking confirmed', colour: 'green' },
    BOOKING_CANCELLED: { text: 'Booking cancelled', colour: 'grey' },
    ACCEPTED: { text: 'Accepted', colour: 'green' },
    NOT_ACCEPTED: { text: 'Not accepted', colour: 'grey' },
    COMPLETED: { text: 'Completed', colour: 'green' },
    MORE_INFORMATION_NEEDED: { text: 'More information needed', colour: 'orange' },
    AWAITING_DECISION: { text: 'Awaiting decision', colour: 'yellow' },
    ON_WAITING_LIST: { text: 'On waiting list', colour: 'yellow' },
    PLACE_OFFERED: { text: 'Place offered', colour: 'yellow' },
    OFFER_ACCEPTED: { text: 'Offer accepted', colour: 'yellow' },
    CANCELLED: { text: 'Cancelled', colour: 'orange' },
    AWAITING_ARRIVAL: { text: 'Awaiting arrival', colour: 'green' },
    UNKNOWN: { text: 'Unknown', colour: 'grey' },
    OFFER_DECLINED_OR_WITHDRAWN: { text: 'Offer declined or withdrawn', colour: 'orange' },
  })[status] || { text: 'Unknown' }
