name: SAS UI E2E tests

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  e2e_test:
    name: "SAS E2E Tests 🧪"
    runs-on: [ self-hosted, hmpps-github-actions-runner ]
    strategy:
      fail-fast: false
      # Add to the matrix to start splitting the tests across multiple shards
      matrix:
        shard: [1]
    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          # Repository is specified to run the workflow from the SAS API repository
          repository: 'ministryofjustice/hmpps-single-accommodation-service-ui'

      - name: Setup Node.js environment
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version-file: '.node-version'
          cache: 'npm'

#      - name: SLSA
#        uses: ministryofjustice/devsecops-actions/sca/slsa@4cd163be7859cd130800d6719d925318826038ea

      - name: Install dependencies
        run: npm ci --no-audit

      - name: Install Playwright
        run: npx playwright install chromium

      - name: Run E2E Tests
        env:
          E2E_BASE_URL: 'https://single-accommodation-service-dev.hmpps.service.justice.gov.uk'
          SAS_E2E_PROBATION_USER_USERNAME: ${{ secrets.E2E_USER_SAS_USER_PP_USERNAME }}
          SAS_E2E_PROBATION_USER_PASSWORD: ${{ secrets.E2E_USER_SAS_USER_PP_PASSWORD }}
        run: npm run test:e2e -- --shard=${{ matrix.shard }}/${{ strategy.job-total }}

      - name: Upload Playwright report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: SAS-E2E-playwright-report-${{ matrix.shard }}-of-${{ strategy.job-total }}
          path: e2e/report
          retention-days: 30
          if-no-files-found: ignore

      - name: Upload E2E artefacts
        if: failure()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: SAS-E2E-artefacts-${{ matrix.shard }}-of-${{ strategy.job-total }}
          path: e2e/artefacts
          retention-days: 30
          if-no-files-found: ignore

  e2e_test_notify_slack:
    name: "E2E test failure notification"
    needs: e2e_test
    if: ${{ always() && needs.e2e_test.result == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification
        uses: ministryofjustice/hmpps-approved-premises-ui/.github/actions/slack_failure_notification@14ed3c52e226afbbb1562dd4ed67d2e665e96788 # main
        with:
          title: "SAS E2E Tests"
          job: "e2e_test"
          channel_id: ${{ vars.SECURITY_ALERTS_SLACK_CHANNEL_ID }}
          slack_bot_token: ${{ secrets.HMPPS_SRE_SLACK_BOT_TOKEN }}
