name: Generate Types

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read
  pull-requests: write

env:
  NODE_ENV: test

jobs:
  generate-types:
    runs-on: [self-hosted, hmpps-github-actions-runner]
    steps:
      - name: Check out code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: 'false'

      - name: Setup Node.js environment
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version-file: '.node-version'
          cache: 'npm'

#      - name: SLSA
#        uses: ministryofjustice/devsecops-actions/sca/slsa@4cd163be7859cd130800d6719d925318826038ea

      - name: Install dependencies
        run: npm ci --no-audit

      - name: Generate Token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Generate Types
        run: npm run generate-types -- ${{ vars.SAS_API_SPEC_URL }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8
        with:
          token: ${{ steps.generate-token.outputs.token }}
          sign-commits: true
          title: 'API model updates'
          commit-message: 'Updating hmpps-single-accommodation-service-api models from OpenAPI specification'
          body: 'Updating hmpps-single-accommodation-service-api models from OpenAPI specification.  This PR was created automatically from the generate-types.yml Workflow'
          delete-branch: true
          branch: update-api-types
